version: '3.8'

services:
  # Serviço da API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestao-escolar-api
    ports:
      - "8000:8000"
    volumes:
      # Volume para persistir o banco de dados SQLite
      - ./data:/app/data
      # Volume para o arquivo de banco SQLite na raiz (se existir)
      - ./escola.db:/app/escola.db
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço opcional para monitoramento (Portainer)
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  portainer_data:

networks:
  default:
    name: gestao-escolar-network